name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moon
        uses: hustcer/setup-moonbit@v1
        with:
          version: latest

      - name: moon version
        run: |
          moon version --all

      - name: install module dependencies
        run: |
          moon update
          moon install

      - name: moon check
        run: moon check

      - name: moon test
        run: moon test
